name: 'App Store Connect API Token'
description: 'App Store Connect API token generator.'
author: 'yuki0n0'
- name: App Store Connect API Token
  uses: yuki0n0/action-appstoreconnect-token@v1.0


branding:
  icon: 'unlock'
  color: 'green'

inputs:
  issuer id:
    description: 'UUID. Can get from App Store Connect.'
    required: true
  key id:
    description: 'Key ID. Can get from App Store Connect.'
    required: true
  key:
    description: 'P8 private key. Can get from App Store Connect.'
    required: true

outputs:
  token:
    description: 'Generated token to use App Store Connect API.'

runs:
  using: 'node12'
  main: 'main.js'
